#!/usr/bin/env php
<?php
/**
 * Part of lyra-cli project.
 *
 * @copyright  Copyright (C) 2018 ${ORGANIZATION}.
 * @license    __LICENSE__
 */

use Lyrasoft\Cli\{
    Application,
    Ioc,
    Service\AppProvider
};
use \Lyrasoft\Cli\Command;

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_file($autoload)) {
    $autoload = __DIR__ . '/../../autoload.php';
}

require $autoload;

define('LYRA_ROOT', __DIR__);
define('LYRA_SOURCE', __DIR__ . '/src');
define('LYRA_TMP', __DIR__ . '/tmp');

$container = Ioc::getContainer();
$container->registerServiceProvider(new AppProvider());

/** @var Application $app */
$app = $container->get(Application::class);

// Register commands
$app->addCommand(Command\PstormCommand::class);
$app->addCommand(Command\GetPrCommand::class);
$app->addCommand(Command\SnifferCommand::class);

try {
    $code = $app->execute();
} catch (\Throwable $e) {
    echo $e;
    exit(255);
}

exit($code);
